import { critical, highlight, primary, secondary, success } from './colors';

export const colorsLight = {
  "surface": secondary[0],
  "surface-background": secondary[80],
  "surface-muted": secondary[40],
  "surface-negative": secondary[860],
  "surface-negativeMuted": secondary[820],
  "surface-primary": primary[50],
  "surface-critical": critical[50],
  "surface-highlight": highlight[50],

  "onSurface-icon": secondary[860],
  "onSurface-iconSuccess": success[300],
  "onSurface-iconCritical": critical[300],
  "onSurface-iconHighlight": highlight[300],
  "onSurface-iconPrimary": primary[300],
  "onSurface-text": secondary[860],
  "onSurface-textMuted": secondary[700],
  "onSurface-textDisabled": secondary[600],
  "onSurface-textNegative": secondary[0],
  "onSurface-textNegativeMuted": secondary[100],
  "onSurface-textNegativeDisabled": secondary[300],
  "onSurface-textSuccess": success[700],
  "onSurface-textCritical": critical[700],
  "onSurface-textHighlight": highlight[700],
  "onSurface-textPrimary": primary[700],
  "onSurface-border": secondary[400],
  "onSurface-borderMuted": secondary[200],
  "onSurface-borderSuccess": success[200],
  "onSurface-borderCritical": critical[200],
  "onSurface-borderHighlight": highlight[200],
  "onSurface-borderPrimary": primary[200],
  "onSurface-onPrimary": primary[800],

  "interactive-secondary": secondary[860],
  "interactive-secondaryDisabled": secondary[600],
  "interactive-secondaryHovered": secondary[900],
  "interactive-secondaryPressed": secondary[500],
  "interactive-success": success[500],
  "interactive-successDisabled": success[700],
  "interactive-successHovered": success[400],
  "interactive-successPressed": success[600],
  "interactive-primary": primary[300],
  "interactive-primaryDisabled": primary[500],
  "interactive-primaryHovered": primary[200],
  "interactive-primaryPressed": primary[400],
  "interactive-critical": critical[500],
  "interactive-criticalDisabled": critical[700],
  "interactive-criticalHovered": critical[400],
  "interactive-criticalPressed": critical[600],
  "interactive-highlight": highlight[500],
  "interactive-highlightDisabled": highlight[700],
  "interactive-highlightHovered": highlight[400],
  "interactive-highlightPressed": highlight[600]
};


//   surfaceBackground: "#E4E6E9",
//   surface: "#FFFFFF",
//   surfaceMuted: "#F0F1F4",
//   surfaceNegative: "#121316",
//   surfaceNegativeMuted: "#202328",
//   surfacePrimary: "#FCE9C6",
//   surfaceCritical: "#FAEFED",
//   surfaceHighlight: "#F3F6FB",
//
//   "surface-background": "#E4E6E9",
//   "surface": "#FFFFFF",
//   "surface-muted": "#F0F1F4",
//   "surface-negative": "#121316",
//   "surface-negative-muted": "#202328",
//   "surface-primary": "#FCE9C6",
//   "surface-critical": "#FAEFED",
//   "surface-highlight": "#F3F6FB",
